baseURL = "https://danielalvarado.org/"
title = "Daniel Alvarado"
theme = "PaperMod"
languageCode = "en-us"

[params]
  author = "Daniel Alvarado"
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowToc = true
  ShowBreadCrumbs = true

[menu]

  [[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 2
